### ISSUE TITLE
Click Error to move cursor there

### ISSUE THREAD

**Issue by SarcevicAntonio** [SvelteLab/SvelteLab#124]
Blocker is the current CodeMirror component that doesn't allow us to access the editor instance directly.

**Comment by SarcevicAntonio** [comment]
I've noticed weirdness in the editor sometimes after switching between tabs.

Writing something doesn't get displayed in the correct place and the file doesn't actually update. 

Not sure if this is an issue with the tabs or the editor. We might want to clean this up and consider using the code mirror directly to unblock this issue.

**Comment by SarcevicAntonio** [comment]
We should consider using [PuruVJ/neocodemirror](https://github.com/PuruVJ/neocodemirror) for this.

**Comment by paoloricciuti** [comment]
> We should consider using [PuruVJ/neocodemirror](https://github.com/PuruVJ/neocodemirror) for this.

I might see if I can swap out the current editor while working on the svelte-check integration

**Comment by SarcevicAntonio** [comment]
svelte-check is now ready to be integrrated, right? @paoloricciuti

**Comment by paoloricciuti** [comment]
> svelte-check is now ready to be integrrated, right? @paoloricciuti

They need to publish the new package...i still have the branch checked out so it should be easy once they do that

**Comment by SarcevicAntonio** [comment]
i see, but you could also prepare the editor swap, right? if thats still on the table for the svelte-check integration at least 😄

**Comment by paoloricciuti** [comment]
Sure, I'll prepare the swap while waiting

**Comment by paoloricciuti** [comment]
Also thanks, I totally forgot of this other part lol

**Comment by SarcevicAntonio** [comment]
its a small feature but would make it more like the og repl ;)
