### ISSUE TITLE
✨ file uploads

### ISSUE THREAD

**Issue by SarcevicAntonio** [SvelteLab/SvelteLab#159]
**Is your feature request related to a problem? Please describe.**
someone on the svelte discord mentioned that this would be a blocker. Uploading assets like images is a pretty common use case we should support. 

**Describe the solution you'd like**
Add uploading files in the file tree. We could also combine this with the drag n drop and support uploading directly in the folder Dropzone.

**Describe alternatives you've considered**
we could also just do a more basic uploader first. Possibly another folder button on the hover of folders with a modal or inline Dropzone?

**Comment by paoloricciuti** [comment]
I thought about this even before launching and I was a bit cautious because at the end of the day every file gets saved in the db so we need to pay extra attention to what we save and the size of it
