### ISSUE TITLE
🐛 Attempt to close tab kills server

### ISSUE THREAD

**Issue by brunnerh** [SvelteLab/SvelteLab#164]
**Describe the bug**
When trying to (or accidentally) closing the tab, the browser will show a warning. If the confirmation is cancelled, the tab stays open but the server is closed.

**To Reproduce**
Close tab/Ctrl + W.

**Expected behavior**
Nothing changes when staying on the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/834235/232250953-9eb4999a-0e80-4f18-99c9-167b9aa61f70.png)

(It states "Try running a script", but there appears to be no way to do so.)

**Desktop (please complete the following information):**

- OS: Win 10, 64 bit
- Browsers:
  - Chrome 111.0.5563.147
  - Firefox 112.0 (64-bit)

**Additional context**
N/A

**Comment by paoloricciuti** [comment]
Mmm I have to check this thanks for reporting...I have an idea about what causes this.

**Comment by paoloricciuti** [comment]
Ok it should be fixed by now...let me know if everything works correctly, in the meantime i'll close this
