### ISSUE TITLE
🐛 Error notification covers last line of code

### ISSUE THREAD

**Issue by theetrain** [SvelteLab/SvelteLab#173]
**Describe the bug**

Hey all 👋 

I noticed the warning or error overlay covers the last line, preventing me from seeing it.

**To Reproduce**

1. Write some code
2. Create a situation that causes an editor warning
3. Try to edit final line of code
4. Notice the final line cannot be seen, but I can edit it

**Expected behavior**

The code area can adjust its height to compensate for the error message.

**Screenshots**

Without a warning (line 25 is visible):

<img width="978" alt="image" src="https://user-images.githubusercontent.com/12798751/233254065-050621d9-bbdd-4d5b-9f3a-a526fbc1d595.png">

With a warning (line 25 is covered):

<img width="972" alt="image" src="https://user-images.githubusercontent.com/12798751/233254099-2e993a5e-4d84-47f9-a778-3590a9085571.png">

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome
- Version: 112.0.5615.137

**Comment by paoloricciuti** [comment]
I'll think on what's the best way to solve this but this is getting fixed for sure, thanks for reporting

**Comment by paoloricciuti** [comment]
Fixed it ☺️

**Comment by theetrain** [comment]
It works well, thank you!
