### ISSUE TITLE
Firefox : Command palette shortcut already occupied✨ 

### ISSUE THREAD

**Issue by cassepipe** [SvelteLab/SvelteLab#175]
Yes, I am that annoying firefox user that asks for firefox not to be forgotten :-)

On Firefox, `Cmd/Ctrl` + `Shift` + `P` is already an native shortcut and will open a new private window.

Could  there be an alternative shortcut/a button to access it ? 
(I believe you can't override a native browser shortcut but I may be wrong and that would be an acceptable solution I think)

**Comment by paoloricciuti** [comment]
Yeah you are not the first person to warn us about this...I'll try to add another shortcut so that the users already knowing Ctrl+shift+P can continue use that and Firefox users can enjoy the palette too

**Comment by paoloricciuti** [comment]
Just pushed a fix for this: now you can open the command palette both with

`(Ctrl|Cmd) + Shift + P` and `(Ctrl|Cmd) + K`

**Comment by cassepipe** [comment]
I guess you need to implement some sort of override for because actually `Ctrl + K` will trigger a search with the default search engine  in Firefox.
I didn't think about it because I am using Ctrl + K on other websites without issues.
Just tested on Sveltelab.dev and it does trigger a search...
Sorry about that
