### ISSUE TITLE
🐛  Open a repo where Svelte is not in root

### ISSUE THREAD

**Issue by KoljaL** [SvelteLab/SvelteLab#187]
**Describe the bug**
If a GitHub repo is opened where the svelte files are not in the root, they could not be loaded.

**To Reproduce**
Try this: https://www.sveltelab.dev/?provider=github&owner=KoljaL&repo=simpleKanban

**Expected behavior**
A way to set the `root` folder

**Comment by paoloricciuti** [comment]
You can also open a path of your repository:

https://sveltelab.dev/github.com/KoljaL/simpleKanban/tree/main/svelte

will open the svelte folder of your github repo. Is that what you are trying to do?

**Comment by KoljaL** [comment]
But I still get the same error:
```
Failed to load url /src/lib/icons/Plus.svelte (resolved id: /home/httpswwwsveltelabdev-n1l0-f0869cv8/src/lib/icons/Plus.svelte) in /home/httpswwwsveltelabdev-n1l0-f0869cv8/src/lib/components/NewTopic.svelte. Does the file exist?
Error: Not found: /src/lib/icons/Plus.svelte
```
edit:
The file is named lowercase `plus.svelte` in the Github Repo, but uppercase `Plus.svelte` in my local Repo.

**Comment by KoljaL** [comment]
But not locally:
<img width="178" alt="grafik" src="https://user-images.githubusercontent.com/55852574/236186723-5e53ec9d-9d4c-4945-8eb5-57b79619d91a.png">
Even after duplicating and renaming, it's not.
Very strange...

**Comment by paoloricciuti** [comment]
Git does not track rename when the only things that change is the case...I think you can use something like git rename command

**Comment by KoljaL** [comment]
Oh, good to know!  
Now it's `Plus.svelte` :-)
