### ISSUE TITLE
✨ we need docs

### ISSUE THREAD

**Issue by paoloricciuti** [SvelteLab/SvelteLab#189]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is._

I think we really need a documentation website (I propose we open another repo for that) and some informational content (we can make a YouTube video showing the platform around). This will help surface every bit of features that we have.

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._

We should create a new repo and connect it to https://docs.sveltelab.dev

**Comment by SarcevicAntonio** [comment]
Not sure I want separate repos. Makes everything hard to sync. With one repo for both changes can include doc updates in one pr

**Comment by paoloricciuti** [comment]
This is true but would also mean that a change in the docs would trigger a redeploy of the main webapp...unless I'm mistaken and there's a way to avoid this

**Comment by SarcevicAntonio** [comment]
I'd like a section in the docs where each command is listed and explained.

**Comment by SarcevicAntonio** [comment]
What do we need to close this?

Maybe a page that explains the interface roughly with a visual breakdown.

Also maybe we add a link more prominently to the header.

**Comment by SarcevicAntonio** [comment]
I'd also like backwards and forwards buttons on each page and a better flow for the pages.
