### ISSUE TITLE
✨ improve command search (Add tags to commands for common words)

### ISSUE THREAD

**Issue by jdgamble555** [SvelteLab/SvelteLab#201]
~~Can we please make TypeScript the default language here! This is the main reason this utility is useful.  Also, if I search for TypeScript in the options, nothing comes up. It is not even clear TS is an option!~~

~~J~~

We should add common keywords related to a command in the search for a command (eg. Typescript for the template)

**Comment by paoloricciuti** [comment]
While I think typescript is the correct default some people might find it wrong for quick prototypes...however if you search for "template" in the command palette you can see that you can make typescript the default template for yourself

**Comment by jdgamble555** [comment]
> some people might find it wrong for quick prototypes

Sure, some people don't like it. That is fair. However, if you do like it, you would want to use it for EVERY prototype if you believe in good programming principles.  There is reason Qwik, Angular, and Vue all use TypeScript as first class support (you can't even disable it).

Removing types is extremely simple.  Copying code from SvelteLab without Types and translating them takes a LOT more time. However, adding them correctly in the first place will create better practices for newbies.

> however if you search for "template" in the command palette

Why would anyone who wants to use TypeScript search for "template" in order to turn it on? I had to scroll through every option to figure how to use it.  TypeScript is a huge feature people want to use.  At the VERY minimum, please allow typescript to come up when you search for "typescript" or "ts." 

It is not clear at all that you even support it, which will keep many users from adopting this tool.

I would suggest maybe a compromise, and you could have a domain "ts.sveltelab.com" where people can share profession code for svelte. (I believe not using types is poor quality).

J

___

I would also argue that the default JS Support should have the JSDoc built-in. Tools like yours that don't default to using good practice will have many people sharing bad JS.  This is where REPL fails in many aspects.

**Comment by paoloricciuti** [comment]
> > some people might find it wrong for quick prototypes
> 
> Sure, some people don't like it. That is fair. However, if you do like it, you would want to use it for EVERY prototype if you believe in good programming principles. There is reason Qwik, Angular, and Vue all use TypeScript as first class support (you can't even disable it).
> 
> Removing types is extremely simple. Copying code from SvelteLab without Types and translating them takes a LOT more time. However, adding them correctly in the first place will create better practices for newbies.
> 
> > however if you search for "template" in the command palette
> 
> Why would anyone who wants to use TypeScript search for "template" in order to turn it on? I had to scroll through every option to figure how to use it. TypeScript is a huge feature people want to use. At the VERY minimum, please allow typescript to come up when you search for "typescript" or "ts."
> 
> It is not clear at all that you even support it, which will keep many users from adopting this tool.
> 
> I would suggest maybe a compromise, and you could have a domain "ts.sveltelab.com" where people can share profession code for svelte. (I believe not using types is poor quality).
> 
> J
> 
> I would also argue that the default JS Support should have the JSDoc built-in. Tools like yours that don't default to using good practice will have many people sharing bad JS. This is where REPL fails in many aspects.

The philosophy behind this REPL just like the og svelte  REPL is to have a place to hack something out without the hassle of setting up the dev environment.

However I do love typescript and I do use it even for simple prototypes. This is also a reason why we are working towards integrating the TS/svelte language server in SvelteLab, to have proper diagnostics and autocompletion. This will probably help with the JSDoc issue.

However I kinda like the idea of adding tags to the commands to help with discoverability. A documentation website is also in the making and that will help with discoverability too. If you are ok with it I will rename this issue to address this tags situation, otherwise I'll open a new issue regarding it

**Comment by jdgamble555** [comment]
Understood. 👍🏼

**Comment by jdgamble555** [comment]
I think I realized my issue here. There needs to be a way to share a default blank setup with TS as the default. Right now, if i can find it, it saves the default as my session, not in the url.


https://ts.svaeltelab.com would work

or

https://sveltelab.com/ts

or something similar would solve this problem. 

J

**Comment by paoloricciuti** [comment]
> I think I realized my issue here. There needs to be a way to share a default blank setup with TS as the default. Right now, if i can find it, it saves the default as my session, not in the url.
> 
> https://ts.svaeltelab.com would work
> 
> or
> 
> https://sveltelab.com/ts
> 
> or something similar would solve this problem.
> 
> J

https://sveltelab.dev?t=typescript

Here it is
