### ISSUE TITLE
🐛 Update language server to support media range syntax

### ISSUE THREAD

**Issue by theetrain** [SvelteLab/SvelteLab#208]
### Describe the bug

When using CSS media query range syntax, which is supported by Svelte, there is an IDE error.

### Reproduction

1. Go to https://www.sveltelab.dev/tp34jdbruzyax30
2. Observe media query works, and yet an error is showing

### Expected behavior

No error should appear.

### Screenshots

<img width="669" alt="image" src="https://github.com/SvelteLab/SvelteLab/assets/12798751/b3112472-bd49-476a-991b-5430022e839f">

### Additional context

Thanks for your effort! 👋

**Comment by paoloricciuti** [comment]
We are currently reworking this to use svelte-check that should fully support this and also remove the need to keep the compiler constantly up to date. If it takes too much time (we first need to wait for  [this PR](https://github.com/sveltejs/language-tools/pull/2012) to close. We might first update the svelte-compiler inside the worker if it takes too much time

**Comment by paoloricciuti** [comment]
@theetrain this should be resolved with the swap to svelte-check
