### ISSUE TITLE
Menu Bar

### ISSUE THREAD

**Issue by SarcevicAntonio** [SvelteLab/SvelteLab#211]
I'd like to create a menu bar for SvelteLab to replace the current header section (Logo, Files Terminal Toggle).

This section will house a more discoverable way to access common SvetlteLab features.

Here is how it could look like:
![image](https://github.com/SvelteLab/SvelteLab/assets/6685200/5f59c56e-245f-4ef0-913e-7ec2582c7c4e)

We could re-use the menu component and create a component to declare the menu bar structure from an object.

My proposal for menu labels and ordering (very open to bike shedding:)

**SvelteLab**:
New Project
New with Template
Set Default Template
—
Login via GitHub
Profile
—
Open Command Palette
Open SvelteLab Docs
Open SvelteLab GitHub Repo
Submit Issue
Join Discord
Credits
Show Intro

**Project**:
Share File Tree Snapshot via URL Hash
Share Project via ID
—
Create Route
Svelte Add
Install Package
Export / Download Project
Format current file
—
Save Project
Fork Project
Rename Project

**Preferences**:
Toggle Theme
Toggle File Tree
Toggle Terminal
Remove Theme Preference
—
Vim Keybindings
Font Preference
Wrap Code
—
Sort Files First
Show From /src

**Comment by paoloricciuti** [comment]
This is not a bad idea IMHO but I would still leave the header as is (so fork, save, login etc would still be visibile in the header) and make a bit more clear the sveltelab is a menu too (or add a third option)...also let's not forget about mobile

**Comment by SarcevicAntonio** [comment]
yes i planned to keep the icons we have already there ;)
thanks for reminding me of mobile :sweat_smile:

**Comment by paoloricciuti** [comment]
this is closable right @SarcevicAntonio ?
