### ISSUE TITLE
Error message on '$lib' imports 

### ISSUE THREAD

**Issue by trasherdk** [SvelteLab/SvelteLab#226]
### Describe the bug

Importing from `$lib` in `+page.svelte` gives errors, but works anyway.

### Reproduction

The errors are available in [The Context API](https://www.sveltelab.dev/1w64p8d5ys6i6zo)

### Expected behavior

Well, the errors should not be present, when the imports clearly works :lau

### Screenshots

![image](https://github.com/SvelteLab/SvelteLab/assets/5003891/286fd7af-89da-4353-a987-3826d2eb054a)

**Comment by paoloricciuti** [comment]
Mmm I bet this has to do with the classic error you get when you have to restart the TS server...we need to add something similar to restart svelte-check

**Comment by paoloricciuti** [comment]
Oh i just realized the error in this repl is because you don't have svelte-preprocess but you are trying to use `lang="ts"` but we do still need to restart svelte-check

**Comment by trasherdk** [comment]
Yes, adding `svelte-preprocess` to the config, got rid of the error messages :smile:
