### ISSUE TITLE
cannot start any webcontainer🐛 

### ISSUE THREAD

**Issue by michapixel** [SvelteLab/SvelteLab#237]
### Describe the bug

i was doing a browser-reload because of some small ui-bug but the webcontainer won't start anymore.

### Reproduction

i guess ...

### Expected behavior

should work ;)

**Comment by paoloricciuti** [comment]
> how fast are you sir, please?
> 
> i think you need a ticket for browsing waaaaayyyy too fast ;)
> 
> i merely typed this

Hahahaha it really depends if i'm on my phone...and regarding the indetification of the problem was already done before this issue
