### ISSUE TITLE
✨ Profile Page Sort: Reverse Order Option 

### ISSUE THREAD

**Issue by SarcevicAntonio** [SvelteLab/SvelteLab#244]
### Describe the problem

~~Searching for a project by looking through my profile is hard, because it's not ordered by anything useful. I don't always want to type to search a repl, also I have multiple ones called "Hello World".~~

@K-Sato1995 added sorting, but we'd like to also have a toggle for reversing order.

### Describe the solution you would like

We want to add a toggle next to the dropdown for reversing the order.

**Comment by SarcevicAntonio** [comment]
@K-Sato1995 I'll just leave this open and update title & description, so no need for a new issue 😄

**Comment by K-Sato1995** [comment]
@SarcevicAntonio 

Sweet! thanks!
