### ISSUE TITLE
✨ Include default .gitignore in exported project

### ISSUE THREAD

**Issue by geoffrich** [SvelteLab/SvelteLab#254]
### Describe the problem

I recently downloaded a project from SvelteLab when helping someone out. I initialized a git repo locally to track the changes I was making, and because there was no .gitignore file, I had to create one myself to ignore the output of the node_modules and .svelte-kit folders.

### Describe the solution you would like

Include a .gitignore by default in SvelteLab (either in the new project template, or just when exporting)

**Comment by paoloricciuti** [comment]
That's a good idea, we removed it initially to bring the amount of files to the minimum and because there were no way to download projects but now that is possible it's absolutely a need. Will add this soon

**Comment by paoloricciuti** [comment]
You know what? It's pretty easy and i'm already on Desktop...i just added them, thanks for the idea @geoffrich

**Comment by geoffrich** [comment]
Super fast turnaround 🔥

**Comment by paoloricciuti** [comment]
> Super fast turnaround 🔥

Hahahahaha I just happen to be awake, at the right moment, with the right equipment.
