### ISSUE TITLE
🐛 "Additional step required" when opening fullscreen view 

### ISSUE THREAD

**Issue by khromov** [SvelteLab/SvelteLab#286]
### Describe the bug

When I try to open the full screen view, I always get the "Additional step requred" screen. Seems to happen both on Firefox and Chrome on Mac. I even tried logging in with StackBlitz as requested but it did not help, I get the below error when trying to "Connect to Project":

Step 1:

![Screenshot 2023-10-25 at 21 18 16](https://github.com/SvelteLab/SvelteLab/assets/1207507/8dc476d3-9624-4b19-a8cc-f337abf52617)

Step 2:

![Screenshot 2023-10-25 at 21 19 11](https://github.com/SvelteLab/SvelteLab/assets/1207507/8b96825e-ce5e-4d02-87a3-13a386743496)

Step 3:

![Screenshot 2023-10-25 at 21 16 36](https://github.com/SvelteLab/SvelteLab/assets/1207507/f1773983-54dd-4024-8aa3-086e9c9f378f)

### Reproduction

Firefox, MacOS 14 Sonoma. Create any project, try to open fullscreen.

### Expected behavior

Project should open in new tab.

**Comment by paoloricciuti** [comment]
Yeah this is unfortunately a problem that the webcontainers API has with Firefox...we can't do much  about it

**Comment by khromov** [comment]
@paoloricciuti I have the same problem on Chrome 118.0.5993.117. Is that expected? Do I need to sign in to StackBlitz to go into full screen? 🤔

**Comment by paoloricciuti** [comment]
> @paoloricciuti I have the same problem on Chrome 118.0.5993.117. Is that expected? Do I need to sign in to StackBlitz to go into full screen? 🤔

I noticed sometimes it happen on chrome too...are you trying to open in incognito by any chance?

**Comment by khromov** [comment]
@paoloricciuti Not incognito, no extensions loaded except standard Chrome ones (Google Docs).

**Comment by paoloricciuti** [comment]
I will try out and eventually report back to stack blitz, thanks for reporting :pray:
