### ISSUE TITLE
✨ "workspace:*" in package.json

### ISSUE THREAD

**Issue by jycouet** [SvelteLab/SvelteLab#288]
### Describe the problem

I would like to open a sub directory of a monorepo, but in this sub directory, I have a few dep vith a value: "workspace:*"

Here is the example:
https://www.sveltelab.dev/?provider=github&owner=jycouet&repo=kitql&branch=main&path=%2Fpackages%2Fvite-plugin-kit-routes

This fail, because "workspace:*" is not good in this context.

### Describe the solution you would like

First, I was thinking about "just" replacing `workspace:*` by `*` at the start of the process.
But in my case, "eslint-config-kitql": "workspace:*" will still fail as eslint-config-kitql will never be published.

Maybe an ability to execute a js file before `npm i`? Like this, I can tune the file before the normal start process?

### Additional context

Do you know how codesandbox or stackblitz handle this?

**Comment by paoloricciuti** [comment]
Can you confirm that this works in stack blitz? To me it seems unlikely because you don't have the whole repository to resolve that package from.

**Comment by jycouet** [comment]
I think that it's not working anywhere! _(and that's normal)_

For `codesandbox`, I just found out that I can create a file `.codesandbox/tasks.json`, with this content:
```
{
  "$schema": "https://codesandbox.io/schemas/tasks.json",
  "setupTasks": ["node .codesandbox/script.js", "pnpm i", "pnpm dev"]
}
```
Then have a file: `.codesandbox/script.js` with
```ts
import fs from 'fs'

const pkg = JSON.parse(fs.readFileSync('./package.json', 'utf-8'))
delete pkg.devDependencies['eslint-config-kitql']
pkg.dependencies['@kitql/helpers'] = '*'
pkg.dependencies['vite-plugin-watch-and-run'] = '*'
fs.writeFileSync('./package.json', JSON.stringify(pkg, null, 2))
```

And it's working like a charm

**Comment by jycouet** [comment]
I'm looking at different solutions as I don't like a "custom" thing like this per platform.
I had a look at `preinstall`, but you know what? `preinstall` is running after the install ^^haha.

So, I think I will have a dedicated project for demo that people can clone, degit, open in SvelteLab.

I'll close the issue if it's ok for you

**Comment by paoloricciuti** [comment]
> I'm looking at different solutions as I don't like a "custom" thing like this per platform. I had a look at `preinstall`, but you know what? `preinstall` is running after the install ^^haha.
> 
> So, I think I will have a dedicated project for demo that people can clone, degit, open in SvelteLab.
> 
> I'll close the issue if it's ok for you

I agree...however the idea of a custom convention on a file to run before install could be good. Only issue is that you can't use any dependency there lol
