### ISSUE TITLE
✨ Easier way to find the import from github command

### ISSUE THREAD

**Issue by Jax-Hax** [SvelteLab/SvelteLab#292]
### Describe the problem

I tried to find the import from github command but I geniunely can't, I keep seeing it be mentioned in the issues but I don't see it anywhere. Idk if I'm just being stupid or it geniunely isn't there, but maybe an easier way to access it would be nice as I don't want to manually import every file

### Describe the solution you would like

An easier way to find import with github

**Comment by paoloricciuti** [comment]
Here's where it's mentioned in the docs https://docs.sveltelab.dev/sharing-and-saving#open-project-from-github

We would love to give more visibility to this feature but we don't have a precise idea of how...do you have any ideas?

**Comment by SarcevicAntonio** [comment]
I'm creating a command for it with a UI that helps you import a project
