### ISSUE TITLE
When trying to save the project I get Can't Save the project🐛 

### ISSUE THREAD

**Issue by overas** [SvelteLab/SvelteLab#296]
### Describe the bug

I can not update and save a project which was saved earlier in my github profile.

### Reproduction

First I login to github with my user account and password. Then I make a new project and rename the default projectname to Test.  After that I start editing the default +page.svelte file and add some html content and save. No problem with saving the project. 

I use the Profile button to navigate to my profile with all my projects. I open the Test project again and edit the html content. When saving the project I get "Can't Save the project" and the project is not updated.
I get the same message with Chrome and Edge.

### Expected behavior

The project Test are going to be saved in my github profile.

### Screenshots

![Can not save project](https://github.com/SvelteLab/SvelteLab/assets/37910044/90d8f1f7-bc72-4021-a46c-eebb5dfbecd9)

### Additional context

Chrome Versjon 120.0.6099.218 (Offisiell delversjon) (64-bit)
Edge Versjon 120.0.2210.133 (Offisiell build) (64-biters)

**Comment by paoloricciuti** [comment]
I think this might be the payload limit from vercel... we are aware of this (if that's it) but the fix is quite complex. Can you share us the link to the project you are trying to open and a brief list of the modification you are trying to make (especially if they are huge)

**Comment by overas** [comment]
I waited 5 minuts and now I can save the project again. I tested again with a new project and I had no problem saving. Maybe this is a Sveltelab stability problem?

**Comment by overas** [comment]
Here is the link I modified https://www.sveltelab.dev/j4s1058lu0wtabl . It is default Hello World with this html code in it: <h1>Tester overskrifter</h1>

**Comment by paoloricciuti** [comment]
Oh than maybe it was just some random issue...let me know if you can constantly reproduce so that I can investigate

**Comment by overas** [comment]
Thanks for a great product and quick help. I am going to report if this happen again.

**Comment by paoloricciuti** [comment]
Glad it helps you 🙏🏼

**Comment by overas** [comment]
Today I have the same problem saving the project. 
I log in to Sveltelab using this url: https://www.sveltelab.dev/?login=true. Then I change the project with Open Menu -> Your Profile. I my profile webpage I choose the Test project. I change <h1>Tester overskrifter66</h1> to <h1>Tester overskrifter67</h1> and hit the Save Project button. Then I get the Can't Save the project.

But I can save the project after changing the text in <h1> tag when I copy the project url: https://www.sveltelab.dev/j4s1058lu0wtabl/ and paste the url in a new tab i Chrome. So I can save when use the url directly i Chrome or Edge, but not when I choose the project from the profile webpage.

**Comment by paoloricciuti** [comment]
> Today I have the same problem saving the project. But with a different method I can save the project.
> 
> Not working: I log in to Sveltelab using this url: https://www.sveltelab.dev/?login=true. Then I change the project with Open Menu -> Your Profile. I my profile webpage I choose the Test project. I change `<h1>Tester overskrifter66</h1> to <h1>Tester overskrifter67</h1>` and hit the Save Project button. Then I get the Can't Save the project.
> 
> Working: But I can save the project after changing the text in `<h1>` tag when I copy the project url: https://www.sveltelab.dev/j4s1058lu0wtabl/ and paste the url in a new tab i Chrome. So I can save when use the url directly i Chrome or Edge, but not when I choose the project from the profile webpage.

Will try to reproduce

**Comment by overas** [comment]
After writing the comment I tried again and now its working to save after choosing the project from the profile webpage and using the project url. It seems Sveltelab or the cloud connection is unstable.

**Comment by paoloricciuti** [comment]
> After writing the comment I tried again and now its working to save after choosing the project from the profile webpage and using the project url. It seems Sveltelab or the cloud connection is unstable.

Yesterday vercel was having some problem but I don't know if it's related

**Comment by overas** [comment]
I hope is a temporary problem. I going to use Sveltelab a few days now so maybe this will be fixed,

**Comment by overas** [comment]
I close the issue, but SvelteLab gives "Can't Save the project" still.

**Comment by paoloricciuti** [comment]
If you can reproduce consistently I can look into it
