### ISSUE TITLE
🐛 Unable to save projects on mobile

### ISSUE THREAD

**Issue by Razorshnegax018** [SvelteLab/SvelteLab#299]
### Describe the bug

While trying to save a project on a mobile device, the progress icon just infinitely spins as nothing happens 

### Reproduction

Step 1. Sign into sveltelab account on mobile device
Step 2. Open and start editing one of your projects
Step 3. Attempt to save

### Expected behavior

I expect that when the save button is tapped, the project will complete the save

### Additional context

iPhone 11, iOS 16. Closed all my tabs, tried a new browser and even new account. None worked

**Comment by paoloricciuti** [comment]
Funnily enough I was just hacking something on sveltelab while you opened this issue. I saved to come see what this was about and it went through with no problem 😄 

Maybe it's related to the iPhone but without more info there's not much I can do. Do you have a way to investigate a bit further? Trying to see the console or stuff like that?

**Comment by Razorshnegax018** [comment]
If I’m being totally honest, it’s probably because I haven’t updated my iPhone to iOS 17 yet. I say this because with my phone webcontainers don’t even work/aren’t supported yet. So I guess I’ll clean up and update
