### ISSUE TITLE
✨ Make tab-size a Editor preference

### ISSUE THREAD

**Issue by PatrickG** [SvelteLab/SvelteLab#301]
### Describe the problem

It seems like the tab-size in the editor is set to `3` and is not configurable in the Editor preferences.
IMO this is a very odd tab size. It get's very obvious when editing a REPL of someone who uses spaces.

### Describe the solution you would like

Make the tab-size configurable in Editor preferences.

**Comment by SarcevicAntonio** [comment]
Thanks for raising and merging 😊✨
